### ISSUE TITLE
`TctColBert.reverse()'s function

### ISSUE THREAD

**Issue by noem-1998** [terrierteam/pyterrier_dr#10]
Heyy,

I'm a bit confused on what the method `TctColBert.reverse()` do? and is it used by any other method internally?
Also, in this line of code:
` Q = Q[:, 4:, :].mean(dim=1) # remove the first 4 tokens (representing [CLS] [ Q ]), and average`
seems stupid to ask but why is [CLS] [ Q ] represeted in 4 tokens and not 2?

Thank you!

**Comment by seanmacavaney** [comment]
Whoops, that was an idea that I was trying out that didn't work. It should be removed from the repository.

Regarding 4, this was the technique used by TCT for representing the [CLS] [Q] prefix. It turns out that the TCT authors did it differently (potentially inadvertently) than the original ColBERT model, which treats [Q] as a single token. By default, the WordPiece tokenizer slits "[Q]" into "[", "Q", "]"; ColBERT paper needed to put special handing in place to treat it as a single token.

Hope this helps!

**Comment by oussaidene** [comment]
Got it! Thank you

**Comment by noem-1998** [comment]
i see. 
Thank you
